In [18]:
import pandas as pd

## Accessing Data

In [19]:
cofee = pd.read_csv("Data/coffee.csv")

In [28]:
cofee.shape

(14, 3)

In [20]:
cofee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

## Learning loc

In [33]:
cofee.loc[[0,2,5],["Units Sold", "Day"]]

   Units Sold        Day
0          25     Monday
2          30    Tuesday
5          25  Wednesday

In [34]:
cofee.loc[0, "Coffee Type"]

'Espresso'

In [41]:
cofee.loc[(cofee["Units Sold"]>30) & (cofee["Day"] == "Saturday") ]

         Day Coffee Type  Units Sold
10  Saturday    Espresso          45
11  Saturday       Latte          35

In [42]:
cofee.loc[0, "Units Sold"] = 20

In [43]:
cofee

          Day Coffee Type  Units Sold
0      Monday    Espresso          20
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

## Learning iloc

In [46]:
cofee.iloc[0 ,2]

20

In [47]:
cofee.iloc[0:10:2]

         Day Coffee Type  Units Sold
0     Monday    Espresso          20
2    Tuesday    Espresso          30
4  Wednesday    Espresso          35
6   Thursday    Espresso          40
8     Friday    Espresso          45

## Learning Query